export default [
  {
    STATIONNAME: 'Aberdeen-Matawan',
    'STATION CODE': 250,
    'PENTA ID': 'AM',
    'ATIS ID': 37169,
    LATITUDE: 40.420161,
    LONGITUDE: -74.223702,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Absecon ',
    'STATION CODE': 196,
    'PENTA ID': 'AB',
    'ATIS ID': 2,
    LATITUDE: 39.4243331,
    LONGITUDE: -74.502094,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Allendale',
    'STATION CODE': 750,
    'PENTA ID': 'AZ',
    'ATIS ID': 151,
    LATITUDE: 41.030902,
    LONGITUDE: -74.130957,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B04',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Allenhurst',
    'STATION CODE': 274,
    'PENTA ID': 'AH',
    'ATIS ID': 4,
    LATITUDE: 40.237659,
    LONGITUDE: -74.006769,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Anderson St',
    'STATION CODE': 424,
    'PENTA ID': 'AS',
    'ATIS ID': 5,
    LATITUDE: 40.894458,
    LONGITUDE: -74.043781,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Annandale',
    'STATION CODE': 370,
    'PENTA ID': 'AN',
    'ATIS ID': 6,
    LATITUDE: 40.645173,
    LONGITUDE: -74.878569,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Asbury Park',
    'STATION CODE': 276,
    'PENTA ID': 'AP',
    'ATIS ID': 8,
    LATITUDE: 40.215359,
    LONGITUDE: -74.014786,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Atco ',
    'STATION CODE': 190,
    'PENTA ID': 'AO',
    'ATIS ID': 9,
    LATITUDE: 39.7835471,
    LONGITUDE: -74.907588,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Atlantic City ',
    'STATION CODE': 198,
    'PENTA ID': 'AC',
    'ATIS ID': 10,
    LATITUDE: 39.3632991,
    LONGITUDE: -74.441486,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Avenel',
    'STATION CODE': 220,
    'PENTA ID': 'AV',
    'ATIS ID': 11,
    LATITUDE: 40.57762,
    LONGITUDE: -74.27753,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Basking Ridge',
    'STATION CODE': 960,
    'PENTA ID': 'BI',
    'ATIS ID': 12,
    LATITUDE: 40.711378,
    LONGITUDE: -74.55527,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Bay Head',
    'STATION CODE': 288,
    'PENTA ID': 'BH',
    'ATIS ID': 13,
    LATITUDE: 40.077178,
    LONGITUDE: -74.046183,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Bay Street',
    'STATION CODE': 624,
    'PENTA ID': 'MC',
    'ATIS ID': 50,
    LATITUDE: 40.808178,
    LONGITUDE: -74.208681,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Belmar',
    'STATION CODE': 280,
    'PENTA ID': 'BS',
    'ATIS ID': 15,
    LATITUDE: 40.18059,
    LONGITUDE: -74.027301,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Berkeley Heights',
    'STATION CODE': 950,
    'PENTA ID': 'BY',
    'ATIS ID': 17,
    LATITUDE: 40.682345,
    LONGITUDE: -74.442649,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Bernardsville',
    'STATION CODE': 962,
    'PENTA ID': 'BV',
    'ATIS ID': 18,
    LATITUDE: 40.716845,
    LONGITUDE: -74.571023,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Bloomfield',
    'STATION CODE': 616,
    'PENTA ID': 'BM',
    'ATIS ID': 154,
    LATITUDE: 40.792709,
    LONGITUDE: -74.200043,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Boonton',
    'STATION CODE': 856,
    'PENTA ID': 'BN',
    'ATIS ID': 20,
    LATITUDE: 40.903378,
    LONGITUDE: -74.407736,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B22',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Bound Brook',
    'STATION CODE': 344,
    'PENTA ID': 'BK',
    'ATIS ID': 21,
    LATITUDE: 40.560929,
    LONGITUDE: -74.530617,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Bradley Beach',
    'STATION CODE': 278,
    'PENTA ID': 'BB',
    'ATIS ID': 22,
    LATITUDE: 40.203751,
    LONGITUDE: -74.018891,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Brick Church',
    'STATION CODE': 516,
    'PENTA ID': 'BU',
    'ATIS ID': 23,
    LATITUDE: 40.7651341,
    LONGITUDE: -74.218612,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Bridgewater',
    'STATION CODE': 350,
    'PENTA ID': 'BW',
    'ATIS ID': 24,
    LATITUDE: 40.559906,
    LONGITUDE: -74.551741,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Broadway',
    'STATION CODE': 730,
    'PENTA ID': 'BF',
    'ATIS ID': 116,
    LATITUDE: 40.922505,
    LONGITUDE: -74.115236,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B03',
    LINE: 'Bergen County',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;BERG',
  },
  {
    STATIONNAME: 'Campbell Hall',
    'STATION CODE': 794,
    'PENTA ID': 'CB',
    'ATIS ID': 135,
    LATITUDE: 41.45103013,
    LONGITUDE: -74.26639559,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Chatham',
    'STATION CODE': 548,
    'PENTA ID': 'CM',
    'ATIS ID': 145,
    LATITUDE: 40.7401371,
    LONGITUDE: -74.384812,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B17',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Cherry Hill ',
    'STATION CODE': 184,
    'PENTA ID': 'CY',
    'ATIS ID': 28,
    LATITUDE: 39.9284471,
    LONGITUDE: -75.041661,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Clifton',
    'STATION CODE': 722,
    'PENTA ID': 'IF',
    'ATIS ID': 46,
    LATITUDE: 40.867998,
    LONGITUDE: -74.153203,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Convent Station ',
    'STATION CODE': 552,
    'PENTA ID': 'CN',
    'ATIS ID': 77,
    LATITUDE: 40.7790401,
    LONGITUDE: -74.443435,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B17',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Cranford',
    'STATION CODE': 310,
    'PENTA ID': 'XC',
    'ATIS ID': 32,
    LATITUDE: 40.655523,
    LONGITUDE: -74.303226,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Delawanna',
    'STATION CODE': 710,
    'PENTA ID': 'DL',
    'ATIS ID': 75,
    LATITUDE: 40.831369,
    LONGITUDE: -74.131262,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Denville',
    'STATION CODE': 563,
    'PENTA ID': 'DV',
    'ATIS ID': 94,
    LATITUDE: 40.8839001,
    LONGITUDE: -74.481513,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Dover',
    'STATION CODE': 566,
    'PENTA ID': 'DO',
    'ATIS ID': 34,
    LATITUDE: 40.8834151,
    LONGITUDE: -74.555887,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B17',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Dunellen',
    'STATION CODE': 338,
    'PENTA ID': 'DN',
    'ATIS ID': 36,
    LATITUDE: 40.590869,
    LONGITUDE: -74.463043,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'East Orange',
    'STATION CODE': 514,
    'PENTA ID': 'EO',
    'ATIS ID': 37,
    LATITUDE: 40.7609771,
    LONGITUDE: -74.210464,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Edison',
    'STATION CODE': 140,
    'PENTA ID': 'ED',
    'ATIS ID': 38,
    LATITUDE: 40.519148,
    LONGITUDE: -74.410972,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B09',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Egg Harbor City ',
    'STATION CODE': 194,
    'PENTA ID': 'EH',
    'ATIS ID': 39,
    LATITUDE: 39.5264411,
    LONGITUDE: -74.648028,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Elberon',
    'STATION CODE': 270,
    'PENTA ID': 'EL',
    'ATIS ID': 40,
    LATITUDE: 40.265292,
    LONGITUDE: -73.99762,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Elizabeth',
    'STATION CODE': 104,
    'PENTA ID': 'EZ',
    'ATIS ID': 41,
    LATITUDE: 40.667857,
    LONGITUDE: -74.215174,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B08',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Emerson',
    'STATION CODE': 438,
    'PENTA ID': 'EN',
    'ATIS ID': 42,
    LATITUDE: 40.975036,
    LONGITUDE: -74.027471,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Essex St',
    'STATION CODE': 422,
    'PENTA ID': 'EX',
    'ATIS ID': 43,
    LATITUDE: 40.878973,
    LONGITUDE: -74.051893,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Fanwood',
    'STATION CODE': 320,
    'PENTA ID': 'FW',
    'ATIS ID': 44,
    LATITUDE: 40.64106,
    LONGITUDE: -74.385003,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Far Hills',
    'STATION CODE': 966,
    'PENTA ID': 'FH',
    'ATIS ID': 45,
    LATITUDE: 40.685712,
    LONGITUDE: -74.633734,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Garfield',
    'STATION CODE': 718,
    'PENTA ID': 'GD',
    'ATIS ID': 115,
    LATITUDE: 40.866669,
    LONGITUDE: -74.10556,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B03',
    LINE: 'Bergen County',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;BERG',
  },
  {
    STATIONNAME: 'Garwood',
    'STATION CODE': 314,
    'PENTA ID': 'GW',
    'ATIS ID': 47,
    LATITUDE: 40.652569,
    LONGITUDE: -74.324794,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Gillette',
    'STATION CODE': 952,
    'PENTA ID': 'GI',
    'ATIS ID': 48,
    LATITUDE: 40.678253,
    LONGITUDE: -74.468317,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Gladstone',
    'STATION CODE': 970,
    'PENTA ID': 'GL',
    'ATIS ID': 49,
    LATITUDE: 40.720284,
    LONGITUDE: -74.666371,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Glen Ridge',
    'STATION CODE': 618,
    'PENTA ID': 'GG',
    'ATIS ID': 19,
    LATITUDE: 40.80059,
    LONGITUDE: -74.204655,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Glen Rock Boro Hall',
    'STATION CODE': 739,
    'PENTA ID': 'GK',
    'ATIS ID': 52,
    LATITUDE: 40.96137,
    LONGITUDE: -74.1293,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B03',
    LINE: 'Bergen County',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;BERG',
  },
  {
    STATIONNAME: 'Glen Rock Main Line',
    'STATION CODE': 738,
    'PENTA ID': 'RS',
    'ATIS ID': 58,
    LATITUDE: 40.962206,
    LONGITUDE: -74.133485,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Hackettstown',
    'STATION CODE': 882,
    'PENTA ID': 'HQ',
    'ATIS ID': 54,
    LATITUDE: 40.8514441,
    LONGITUDE: -74.835352,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '882',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Hamilton',
    'STATION CODE': 176,
    'PENTA ID': 'HL',
    'ATIS ID': 32905,
    LATITUDE: 40.255309,
    LONGITUDE: -74.70412,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B10',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Hammonton ',
    'STATION CODE': 192,
    'PENTA ID': 'HN',
    'ATIS ID': 55,
    LATITUDE: 39.6316731,
    LONGITUDE: -74.79946,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Harriman',
    'STATION CODE': 792,
    'PENTA ID': 'RM',
    'ATIS ID': 149,
    LATITUDE: 41.29337582,
    LONGITUDE: -74.14002029,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Hawthorne',
    'STATION CODE': 736,
    'PENTA ID': 'HW',
    'ATIS ID': 126,
    LATITUDE: 40.942539,
    LONGITUDE: -74.152411,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Hazlet',
    'STATION CODE': 252,
    'PENTA ID': 'HZ',
    'ATIS ID': 59,
    LATITUDE: 40.415385,
    LONGITUDE: -74.190393,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'High Bridge',
    'STATION CODE': 374,
    'PENTA ID': 'HG',
    'ATIS ID': 60,
    LATITUDE: 40.666884,
    LONGITUDE: -74.895863,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Highland Ave',
    'STATION CODE': 520,
    'PENTA ID': 'HI',
    'ATIS ID': 61,
    LATITUDE: 40.7668631,
    LONGITUDE: -74.243741,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Hillsdale',
    'STATION CODE': 442,
    'PENTA ID': 'HD',
    'ATIS ID': 62,
    LATITUDE: 41.002414,
    LONGITUDE: -74.041033,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Hoboken',
    'STATION CODE': 999,
    'PENTA ID': 'HB',
    'ATIS ID': 63,
    LATITUDE: 40.734843,
    LONGITUDE: -74.028046,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '999',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Ho-Ho-Kus',
    'STATION CODE': 746,
    'PENTA ID': 'UF',
    'ATIS ID': 131,
    LATITUDE: 40.997369,
    LONGITUDE: -74.113521,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B04',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Jersey Avenue',
    'STATION CODE': 146,
    'PENTA ID': 'JA',
    'ATIS ID': 32906,
    LATITUDE: 40.476912,
    LONGITUDE: -74.467363,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B09',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Kingsland',
    'STATION CODE': 706,
    'PENTA ID': 'KG',
    'ATIS ID': 14,
    LATITUDE: 40.810121,
    LONGITUDE: -74.117334,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Lake Hopatcong',
    'STATION CODE': 876,
    'PENTA ID': 'HP',
    'ATIS ID': 67,
    LATITUDE: 40.9042191,
    LONGITUDE: -74.665697,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B19',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Lebanon',
    'STATION CODE': 368,
    'PENTA ID': 'ON',
    'ATIS ID': 68,
    LATITUDE: 40.636905,
    LONGITUDE: -74.835766,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Lincoln Park',
    'STATION CODE': 848,
    'PENTA ID': 'LP',
    'ATIS ID': 69,
    LATITUDE: 40.924138,
    LONGITUDE: -74.301826,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B22',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Linden',
    'STATION CODE': 110,
    'PENTA ID': 'LI',
    'ATIS ID': 70,
    LATITUDE: 40.629485,
    LONGITUDE: -74.251772,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B08',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Lindenwold ',
    'STATION CODE': 188,
    'PENTA ID': 'LW',
    'ATIS ID': 71,
    LATITUDE: 39.8338091,
    LONGITUDE: -75.000314,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Little Falls',
    'STATION CODE': 838,
    'PENTA ID': 'FA',
    'ATIS ID': 72,
    LATITUDE: 40.880669,
    LONGITUDE: -74.235372,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B22',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Little Silver',
    'STATION CODE': 264,
    'PENTA ID': 'LS',
    'ATIS ID': 73,
    LATITUDE: 40.326715,
    LONGITUDE: -74.041054,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Long Branch',
    'STATION CODE': 268,
    'PENTA ID': 'LB',
    'ATIS ID': 74,
    LATITUDE: 40.297145,
    LONGITUDE: -73.988331,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '268',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Lyndhurst',
    'STATION CODE': 708,
    'PENTA ID': 'LN',
    'ATIS ID': 66,
    LATITUDE: 40.816475,
    LONGITUDE: -74.124164,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Lyons',
    'STATION CODE': 958,
    'PENTA ID': 'LY',
    'ATIS ID': 76,
    LATITUDE: 40.684844,
    LONGITUDE: -74.54947,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Madison',
    'STATION CODE': 550,
    'PENTA ID': 'MA',
    'ATIS ID': 27,
    LATITUDE: 40.7570281,
    LONGITUDE: -74.415105,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Mahwah',
    'STATION CODE': 756,
    'PENTA ID': 'MZ',
    'ATIS ID': 38417,
    LATITUDE: 41.094416,
    LONGITUDE: -74.14662,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B04',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Manasquan',
    'STATION CODE': 284,
    'PENTA ID': 'SQ',
    'ATIS ID': 79,
    LATITUDE: 40.120573,
    LONGITUDE: -74.047688,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Maplewood',
    'STATION CODE': 532,
    'PENTA ID': 'MW',
    'ATIS ID': 140,
    LATITUDE: 40.7311491,
    LONGITUDE: -74.275427,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Meadowlands',
    'STATION CODE': 410,
    'PENTA ID': 'XU',
    'ATIS ID': 40570,
    LATITUDE: 40.813778,
    LONGITUDE: -74.07431,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'N/A',
    LINE: 'Sports Line',
    LINEABBREVIATION: 'SL',
  },
  {
    STATIONNAME: 'Metropark',
    'STATION CODE': 126,
    'PENTA ID': 'MP',
    'ATIS ID': 83,
    LATITUDE: 40.56864,
    LONGITUDE: -74.329394,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B09',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Metuchen',
    'STATION CODE': 134,
    'PENTA ID': 'MU',
    'ATIS ID': 84,
    LATITUDE: 40.540736,
    LONGITUDE: -74.360671,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B09',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Middletown NY',
    'STATION CODE': 795,
    'PENTA ID': 'MD',
    'ATIS ID': 26,
    LATITUDE: 41.45733927,
    LONGITUDE: -74.37035708,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Middletown; NJ',
    'STATION CODE': 254,
    'PENTA ID': 'MI',
    'ATIS ID': 85,
    LATITUDE: 40.38978,
    LONGITUDE: -74.116131,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Millburn',
    'STATION CODE': 534,
    'PENTA ID': 'MB',
    'ATIS ID': 81,
    LATITUDE: 40.7256221,
    LONGITUDE: -74.303755,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Millington',
    'STATION CODE': 956,
    'PENTA ID': 'GO',
    'ATIS ID': 88,
    LATITUDE: 40.673515,
    LONGITUDE: -74.523606,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Monmouth Park',
    'STATION CODE': 266,
    'PENTA ID': 'MK',
    'ATIS ID': 31696,
    LATITUDE: 40.31345143,
    LONGITUDE: -74.01514732,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Montclair Heights',
    'STATION CODE': 832,
    'PENTA ID': 'HS',
    'ATIS ID': 89,
    LATITUDE: 40.857536,
    LONGITUDE: -74.2025,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '832',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Montclair State University',
    'STATION CODE': 834,
    'PENTA ID': 'UV',
    'ATIS ID': 38081,
    LATITUDE: 40.86978387,
    LONGITUDE: -74.19743445,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '834',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Montvale',
    'STATION CODE': 448,
    'PENTA ID': 'ZM',
    'ATIS ID': 90,
    LATITUDE: 41.040879,
    LONGITUDE: -74.029152,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '448',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Morris Plains',
    'STATION CODE': 560,
    'PENTA ID': 'MX',
    'ATIS ID': 92,
    LATITUDE: 40.8286391,
    LONGITUDE: -74.478197,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B17',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Morristown',
    'STATION CODE': 558,
    'PENTA ID': 'MR',
    'ATIS ID': 30,
    LATITUDE: 40.7971131,
    LONGITUDE: -74.474086,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Mount Arlington',
    'STATION CODE': 874,
    'PENTA ID': 'HV',
    'ATIS ID': 39472,
    LATITUDE: 40.8965901,
    LONGITUDE: -74.632731,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B19',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Mount Olive',
    'STATION CODE': 880,
    'PENTA ID': 'OL',
    'ATIS ID': 93,
    LATITUDE: 40.9073761,
    LONGITUDE: -74.730653,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B19',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Mount Tabor',
    'STATION CODE': 562,
    'PENTA ID': 'TB',
    'ATIS ID': 91,
    LATITUDE: 40.8759041,
    LONGITUDE: -74.481915,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B18',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Mountain Ave',
    'STATION CODE': 830,
    'PENTA ID': 'MS',
    'ATIS ID': 150,
    LATITUDE: 40.848715,
    LONGITUDE: -74.205306,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Mountain Lakes',
    'STATION CODE': 858,
    'PENTA ID': 'ML',
    'ATIS ID': 96,
    LATITUDE: 40.885947,
    LONGITUDE: -74.433604,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B22',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Mountain Station',
    'STATION CODE': 522,
    'PENTA ID': 'MT',
    'ATIS ID': 95,
    LATITUDE: 40.7553671,
    LONGITUDE: -74.253024,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Mountain View Wayne',
    'STATION CODE': 842,
    'PENTA ID': 'MV',
    'ATIS ID': 98,
    LATITUDE: 40.914402,
    LONGITUDE: -74.268158,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B22',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Murray Hill',
    'STATION CODE': 948,
    'PENTA ID': 'MH',
    'ATIS ID': 99,
    LATITUDE: 40.69507,
    LONGITUDE: -74.403134,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Nanuet',
    'STATION CODE': 457,
    'PENTA ID': 'NN',
    'ATIS ID': 100,
    LATITUDE: 41.090015,
    LONGITUDE: -74.014794,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B21',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Netcong',
    'STATION CODE': 878,
    'PENTA ID': 'NT',
    'ATIS ID': 101,
    LATITUDE: 40.8975541,
    LONGITUDE: -74.707317,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B19',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Netherwood',
    'STATION CODE': 326,
    'PENTA ID': 'NE',
    'ATIS ID': 102,
    LATITUDE: 40.629148,
    LONGITUDE: -74.403455,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'New Bridge Landing',
    'STATION CODE': 430,
    'PENTA ID': 'NH',
    'ATIS ID': 110,
    LATITUDE: 40.910856,
    LONGITUDE: -74.035044,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'New Brunswick',
    'STATION CODE': 144,
    'PENTA ID': 'NB',
    'ATIS ID': 103,
    LATITUDE: 40.497278,
    LONGITUDE: -74.445751,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B09',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'New Providence',
    'STATION CODE': 942,
    'PENTA ID': 'NV',
    'ATIS ID': 104,
    LATITUDE: 40.712022,
    LONGITUDE: -74.386501,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'New York Penn Station',
    'STATION CODE': 0,
    'PENTA ID': 'NY',
    'ATIS ID': 105,
    LATITUDE: 40.750046,
    LONGITUDE: -73.992358,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B01',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Newark Airport',
    'STATION CODE': 101,
    'PENTA ID': 'NA',
    'ATIS ID': 37953,
    LATITUDE: 40.704415,
    LONGITUDE: -74.190717,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B08',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Newark Broad St',
    'STATION CODE': 508,
    'PENTA ID': 'ND',
    'ATIS ID': 106,
    LATITUDE: 40.747621,
    LONGITUDE: -74.171943,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '508',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Newark Penn Station',
    'STATION CODE': 100,
    'PENTA ID': 'NP',
    'ATIS ID': 107,
    LATITUDE: 40.734221,
    LONGITUDE: -74.164554,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '100',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'North Branch',
    'STATION CODE': 360,
    'PENTA ID': 'OR',
    'ATIS ID': 108,
    LATITUDE: 40.59202,
    LONGITUDE: -74.683802,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'North Elizabeth',
    'STATION CODE': 102,
    'PENTA ID': 'NZ',
    'ATIS ID': 109,
    LATITUDE: 40.680265,
    LONGITUDE: -74.206165,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B08',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Oradell',
    'STATION CODE': 436,
    'PENTA ID': 'OD',
    'ATIS ID': 111,
    LATITUDE: 40.953478,
    LONGITUDE: -74.029983,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Orange',
    'STATION CODE': 518,
    'PENTA ID': 'OG',
    'ATIS ID': 112,
    LATITUDE: 40.7718831,
    LONGITUDE: -74.233103,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Ottisville',
    'STATION CODE': 796,
    'PENTA ID': 'OS',
    'ATIS ID': 86,
    LATITUDE: 41.47176149,
    LONGITUDE: -74.52922501,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Park Ridge',
    'STATION CODE': 446,
    'PENTA ID': 'PV',
    'ATIS ID': 114,
    LATITUDE: 41.032305,
    LONGITUDE: -74.036164,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Passaic',
    'STATION CODE': 716,
    'PENTA ID': 'PS',
    'ATIS ID': 43599,
    LATITUDE: 40.849413,
    LONGITUDE: -74.13393,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Paterson',
    'STATION CODE': 728,
    'PENTA ID': 'RN',
    'ATIS ID': 121,
    LATITUDE: 40.914887,
    LONGITUDE: -74.16733,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B27',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Peapack',
    'STATION CODE': 968,
    'PENTA ID': 'PC',
    'ATIS ID': 117,
    LATITUDE: 40.708794,
    LONGITUDE: -74.658469,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Pearl River',
    'STATION CODE': 455,
    'PENTA ID': 'PQ',
    'ATIS ID': 118,
    LATITUDE: 41.058181,
    LONGITUDE: -74.022317,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B21',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Pennsauken ',
    'STATION CODE': 183,
    'PENTA ID': 'PN',
    'ATIS ID': 43298,
    LATITUDE: 39.9777691,
    LONGITUDE: -75.061796,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Perth Amboy',
    'STATION CODE': 238,
    'PENTA ID': 'PE',
    'ATIS ID': 119,
    LATITUDE: 40.509398,
    LONGITUDE: -74.273752,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Philadelphia ',
    'STATION CODE': 182,
    'PENTA ID': 'PH',
    'ATIS ID': 1,
    LATITUDE: 39.9565651,
    LONGITUDE: -75.182327,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B25',
    LINE: 'Atlantic City Rail Line',
    LINEABBREVIATION: 'ACRL;ATLC',
  },
  {
    STATIONNAME: 'Plainfield',
    'STATION CODE': 334,
    'PENTA ID': 'PF',
    'ATIS ID': 120,
    LATITUDE: 40.618425,
    LONGITUDE: -74.420163,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Plauderville',
    'STATION CODE': 724,
    'PENTA ID': 'PL',
    'ATIS ID': 29,
    LATITUDE: 40.884916,
    LONGITUDE: -74.102695,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B03',
    LINE: 'Bergen County',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;BERG',
  },
  {
    STATIONNAME: 'Point Pleasant Beach',
    'STATION CODE': 286,
    'PENTA ID': 'PP',
    'ATIS ID': 122,
    LATITUDE: 40.092718,
    LONGITUDE: -74.048191,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Port Jervis',
    'STATION CODE': 797,
    'PENTA ID': 'PO',
    'ATIS ID': 113,
    LATITUDE: 41.37461312,
    LONGITUDE: -74.69511148,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Princeton',
    'STATION CODE': 172,
    'PENTA ID': 'PR',
    'ATIS ID': 124,
    LATITUDE: 40.3420881,
    LONGITUDE: -74.65887,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B11',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'PRIN',
  },
  {
    STATIONNAME: 'Princeton Junction',
    'STATION CODE': 164,
    'PENTA ID': 'PJ',
    'ATIS ID': 125,
    LATITUDE: 40.316316,
    LONGITUDE: -74.623753,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B09',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC;PRIN',
  },
  {
    STATIONNAME: 'Radburn',
    'STATION CODE': 732,
    'PENTA ID': 'FZ',
    'ATIS ID': 25,
    LATITUDE: 40.939916,
    LONGITUDE: -74.121614,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B03',
    LINE: 'Bergen County',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;BERG',
  },
  {
    STATIONNAME: 'Rahway',
    'STATION CODE': 116,
    'PENTA ID': 'RH',
    'ATIS ID': 127,
    LATITUDE: 40.606338,
    LONGITUDE: -74.276692,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B08',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Ramsey',
    'STATION CODE': 752,
    'PENTA ID': 'RY',
    'ATIS ID': 3,
    LATITUDE: 41.056422,
    LONGITUDE: -74.141877,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B04',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Ramsey Route 17',
    'STATION CODE': 754,
    'PENTA ID': '17',
    'ATIS ID': 128,
    LATITUDE: 41.07513,
    LONGITUDE: -74.145485,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B04',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Raritan',
    'STATION CODE': 356,
    'PENTA ID': 'RA',
    'ATIS ID': 129,
    LATITUDE: 40.571007,
    LONGITUDE: -74.634364,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Red Bank',
    'STATION CODE': 260,
    'PENTA ID': 'RB',
    'ATIS ID': 130,
    LATITUDE: 40.348284,
    LONGITUDE: -74.074538,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Ridgewood',
    'STATION CODE': 742,
    'PENTA ID': 'RW',
    'ATIS ID': 51,
    LATITUDE: 40.980629,
    LONGITUDE: -74.120592,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': '742',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'River Edge',
    'STATION CODE': 432,
    'PENTA ID': 'RG',
    'ATIS ID': 132,
    LATITUDE: 40.935146,
    LONGITUDE: -74.02914,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Roselle Park',
    'STATION CODE': 306,
    'PENTA ID': 'RL',
    'ATIS ID': 31,
    LATITUDE: 40.667152,
    LONGITUDE: -74.26632,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Rutherford',
    'STATION CODE': 712,
    'PENTA ID': 'RF',
    'ATIS ID': 33,
    LATITUDE: 40.828248,
    LONGITUDE: -74.100563,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B03',
    LINE: 'Bergen County',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;BERG',
  },
  {
    STATIONNAME: 'Salisbury Mills-Cornwall',
    'STATION CODE': 793,
    'PENTA ID': 'CW',
    'ATIS ID': 57,
    LATITUDE: 41.43708193,
    LONGITUDE: -74.10186961,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Secaucus Junction Lower',
    'STATION CODE': 10,
    'PENTA ID': 'TS',
    'ATIS ID': 38187,
    LATITUDE: 40.76136,
    LONGITUDE: -74.07575,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B06',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Secaucus Junction Upper',
    'STATION CODE': 10,
    'PENTA ID': 'SE',
    'ATIS ID': 38174,
    LATITUDE: 40.761188,
    LONGITUDE: -74.075821,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B01',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Short Hills',
    'STATION CODE': 536,
    'PENTA ID': 'RT',
    'ATIS ID': 87,
    LATITUDE: 40.7252491,
    LONGITUDE: -74.323754,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Sloatsburg',
    'STATION CODE': 790,
    'PENTA ID': 'XG',
    'ATIS ID': 144,
    LATITUDE: 41.15715264,
    LONGITUDE: -74.19107015,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Somerville',
    'STATION CODE': 354,
    'PENTA ID': 'SM',
    'ATIS ID': 138,
    LATITUDE: 40.566075,
    LONGITUDE: -74.61397,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'South Amboy',
    'STATION CODE': 240,
    'PENTA ID': 'CH',
    'ATIS ID': 139,
    LATITUDE: 40.484308,
    LONGITUDE: -74.28014,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'South Orange',
    'STATION CODE': 524,
    'PENTA ID': 'SO',
    'ATIS ID': 97,
    LATITUDE: 40.7459521,
    LONGITUDE: -74.260538,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Spring Lake',
    'STATION CODE': 282,
    'PENTA ID': 'LA',
    'ATIS ID': 141,
    LATITUDE: 40.150557,
    LONGITUDE: -74.035481,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B13',
    LINE: 'North Jersey Coast Line; North Jersey Coast Line (Bay Head)',
    LINEABBREVIATION: 'NJCL;NJCLL',
  },
  {
    STATIONNAME: 'Spring Valley',
    'STATION CODE': 459,
    'PENTA ID': 'SV',
    'ATIS ID': 142,
    LATITUDE: 41.111978,
    LONGITUDE: -74.043991,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B21',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Stirling',
    'STATION CODE': 954,
    'PENTA ID': 'SG',
    'ATIS ID': 143,
    LATITUDE: 40.674581,
    LONGITUDE: -74.493723,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B17',
    LINE: 'Gladstone',
    LINEABBREVIATION: 'MNEG;GLAD',
  },
  {
    STATIONNAME: 'Suffern',
    'STATION CODE': 758,
    'PENTA ID': 'SF',
    'ATIS ID': 78,
    LATITUDE: 41.11354,
    LONGITUDE: -74.153442,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': '758',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Summit',
    'STATION CODE': 542,
    'PENTA ID': 'ST',
    'ATIS ID': 136,
    LATITUDE: 40.7165491,
    LONGITUDE: -74.357807,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B16',
    LINE: 'Morris & Essex',
    LINEABBREVIATION: 'M&E;MNE',
  },
  {
    STATIONNAME: 'Teterboro',
    'STATION CODE': 418,
    'PENTA ID': 'TE',
    'ATIS ID': 146,
    LATITUDE: 40.864858,
    LONGITUDE: -74.062676,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Towaco',
    'STATION CODE': 850,
    'PENTA ID': 'TO',
    'ATIS ID': 147,
    LATITUDE: 40.922809,
    LONGITUDE: -74.343842,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B22',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Trenton',
    'STATION CODE': 180,
    'PENTA ID': 'TR',
    'ATIS ID': 148,
    LATITUDE: 40.218515,
    LONGITUDE: -74.753926,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B10',
    LINE: 'Northeast Corridor Line',
    LINEABBREVIATION: 'NEC',
  },
  {
    STATIONNAME: 'Tuxedo',
    'STATION CODE': 791,
    'PENTA ID': 'TC',
    'ATIS ID': 137,
    LATITUDE: 41.19419013,
    LONGITUDE: -74.18510519,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B05',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Union',
    'STATION CODE': 304,
    'PENTA ID': 'US',
    'ATIS ID': 38105,
    LATITUDE: 40.683663,
    LONGITUDE: -74.238605,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Upper Montclair',
    'STATION CODE': 824,
    'PENTA ID': 'UM',
    'ATIS ID': 153,
    LATITUDE: 40.8420041,
    LONGITUDE: -74.209368,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Waldwick',
    'STATION CODE': 748,
    'PENTA ID': 'WK',
    'ATIS ID': 64,
    LATITUDE: 41.012734,
    LONGITUDE: -74.123412,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B04',
    LINE: 'Main Line',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;MAIN',
  },
  {
    STATIONNAME: 'Walnut St',
    'STATION CODE': 820,
    'PENTA ID': 'WA',
    'ATIS ID': 123,
    LATITUDE: 40.817218,
    LONGITUDE: -74.20963,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Watchung Ave',
    'STATION CODE': 822,
    'PENTA ID': 'WG',
    'ATIS ID': 152,
    LATITUDE: 40.829516,
    LONGITUDE: -74.206934,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Watsessing',
    'STATION CODE': 614,
    'PENTA ID': 'WT',
    'ATIS ID': 35,
    LATITUDE: 40.782743,
    LONGITUDE: -74.198451,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B15',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Wayne/ Rt 23',
    'STATION CODE': 840,
    'PENTA ID': '23',
    'ATIS ID': 39635,
    LATITUDE: 40.900254,
    LONGITUDE: -74.256971,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B22',
    LINE: 'Montclair-Boonton Line',
    LINEABBREVIATION: 'MOBO;BNTN;MNBTN',
  },
  {
    STATIONNAME: 'Wesmont',
    'STATION CODE': 714,
    'PENTA ID': 'WM',
    'ATIS ID': 134,
    LATITUDE: 40.854979,
    LONGITUDE: -74.096951,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B03',
    LINE: 'Bergen County',
    LINEABBREVIATION: 'MNBNP;MBPJ;MNBN;BERG',
  },
  {
    STATIONNAME: 'Westfield',
    'STATION CODE': 316,
    'PENTA ID': 'WF',
    'ATIS ID': 155,
    LATITUDE: 40.649448,
    LONGITUDE: -74.347629,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Westwood',
    'STATION CODE': 440,
    'PENTA ID': 'WW',
    'ATIS ID': 156,
    LATITUDE: 40.990817,
    LONGITUDE: -74.032696,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'White House',
    'STATION CODE': 364,
    'PENTA ID': 'WH',
    'ATIS ID': 157,
    LATITUDE: 40.615613,
    LONGITUDE: -74.77066,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B20',
    LINE: 'Raritan Valley Line',
    LINEABBREVIATION: 'RVL; RARV',
  },
  {
    STATIONNAME: 'Woodbridge',
    'STATION CODE': 226,
    'PENTA ID': 'WB',
    'ATIS ID': 158,
    LATITUDE: 40.55661,
    LONGITUDE: -74.277751,
    'ADA ACCESSIBLE': 1,
    'BRANCH ID': 'B12',
    LINE: 'North Jersey Coast Line',
    LINEABBREVIATION: 'NJCL',
  },
  {
    STATIONNAME: 'Woodcliff Lake',
    'STATION CODE': 444,
    'PENTA ID': 'WL',
    'ATIS ID': 159,
    LATITUDE: 41.021078,
    LONGITUDE: -74.040775,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
  {
    STATIONNAME: 'Wood-Ridge',
    'STATION CODE': 412,
    'PENTA ID': 'WR',
    'ATIS ID': 160,
    LATITUDE: 40.843974,
    LONGITUDE: -74.078719,
    'ADA ACCESSIBLE': 0,
    'BRANCH ID': 'B02',
    LINE: 'Pascack Valley Line',
    LINEABBREVIATION: 'PVL;PASC',
  },
];
