export default {
  name: 'RAIL',
  title: 'NJ TRANSIT RAIL ADVISORIES',
  publish_date: '20240620 14:08:58',
  lines: [
    {
      name: 'NJCL',
      ALERT: [
        {
          advisory_id: '1766672',
          pub_date: '20240620 14:04:43',
          text: 'NJCL train #3243, the 2:23 PM arrival into Long Branch, is up to 15 min. late due to track maintenance.',
          advisory_alert: '0',
          link: 'https://www.njtransit.com/node/1766672',
        },
      ],
      STATION_ADVISORY: [
        {
          advisory_id: '1766408',
          pub_date: '20240620 08:17:31',
          text: 'South Amboy Station: Eastbound Elevator No. 2 (Overhead Walkway/Mason Street) Temporarily Out of Service - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1766408',
        },
        {
          advisory_id: '1766297',
          pub_date: '20240620 06:58:39',
          text: 'UPDATE: Newark Penn Station: Track 1-PATH Passenger Elevator 37 Returned to Service - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1766297',
        },
        {
          advisory_id: '1755470',
          pub_date: '20240528 08:12:53',
          text: 'Hoboken Terminal: Women’s Restroom Closed for Renovation – Saturday, June 8, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755470',
        },
        {
          advisory_id: '1746980',
          pub_date: '20240506 13:41:14',
          text: 'Monmouth Park Rail Station: Seasonal Station Service Returns – Beginning Saturday, May 11, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1746980',
        },
        {
          advisory_id: '1731699',
          pub_date: '20240326 12:04:00',
          text: 'Newark Penn Station: Track 5 Passenger Elevator 42 Temporarily Out of Service - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1731699',
        },
        {
          advisory_id: '1679199',
          pub_date: '20231103 12:19:06',
          text: 'Asbury Park Transportation Center: Limited Platform Access to Track 1 (Bay Head) – Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1679199',
        },
        {
          advisory_id: '1668803',
          pub_date: '20231011 10:09:22',
          text: 'Elberon Station: Rehabilitation Project – Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1668803',
        },
        {
          advisory_id: '1667201',
          pub_date: '20231006 07:26:38',
          text: 'Secaucus Junction: Track 2 Partial Eastbound Platform Closure - Effective October 5, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1667201',
        },
        {
          advisory_id: '1614725',
          pub_date: '20230609 12:40:33',
          text: 'North Elizabeth Station: Eastbound and Westbound Partial Platform Closure - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1614725',
        },
        {
          advisory_id: '1575048',
          pub_date: '20230208 11:25:49',
          text: 'Rahway Station: Eastbound Staircase Closed for Repairs - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1575048',
        },
        {
          advisory_id: '1571733',
          pub_date: '20230127 09:14:15',
          text: 'Perth Amboy Station Enhancement Project Update – Beginning Monday, January 30, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1571733',
        },
        {
          advisory_id: '1470775',
          pub_date: '20220127 10:38:20',
          text: 'Hoboken Terminal: Boarding Changes for Resiliency Project - Beginning February 2022',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1470775',
        },
      ],
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
        {
          advisory_id: '1755614',
          pub_date: '20240528 14:52:30',
          text: 'Northeast Corridor and North Jersey Coast Line: Possible Delays due to Boarding/Detraining Adjustments – Beginning Friday, June 7, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755614',
        },
        {
          advisory_id: '1590805',
          pub_date: '20230328 13:32:56',
          text: 'Northeast Corridor, North Jersey Coast Line and Morris and Essex Lines: Possible Delays due to Infrastructure Maintenance and Construction of Future Improvements – Weekends Until Further Notice',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1590805',
        },
      ],
    },
    {
      name: 'NEC',
      ALERT: [
        {
          advisory_id: '1766669',
          pub_date: '20240620 14:01:02',
          text: 'NEC train #3847, the 1:32 PM departure from PSNY to Trenton, was cancelled due to mechanical issues. Please take train #3849, the 2:07 PM departure from PSNY.',
          advisory_alert: '0',
          link: 'https://www.njtransit.com/node/1766669',
        },
      ],
      STATION_ADVISORY: [
        {
          advisory_id: '1766297',
          pub_date: '20240620 06:58:39',
          text: 'UPDATE: Newark Penn Station: Track 1-PATH Passenger Elevator 37 Returned to Service - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1766297',
        },
        {
          advisory_id: '1731699',
          pub_date: '20240326 12:04:00',
          text: 'Newark Penn Station: Track 5 Passenger Elevator 42 Temporarily Out of Service - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1731699',
        },
        {
          advisory_id: '1667201',
          pub_date: '20231006 07:26:38',
          text: 'Secaucus Junction: Track 2 Partial Eastbound Platform Closure - Effective October 5, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1667201',
        },
        {
          advisory_id: '1619372',
          pub_date: '20230623 12:03:40',
          text: 'New Brunswick Station: Escalator Upgrades Project and Staircase Closure - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1619372',
        },
        {
          advisory_id: '1614725',
          pub_date: '20230609 12:40:33',
          text: 'North Elizabeth Station: Eastbound and Westbound Partial Platform Closure - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1614725',
        },
        {
          advisory_id: '1575141',
          pub_date: '20230208 14:40:56',
          text: 'Hamilton Station: Westbound Escalator Out of Service for Long-Term Upgrade Work - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1575141',
        },
        {
          advisory_id: '1575048',
          pub_date: '20230208 11:25:49',
          text: 'Rahway Station: Eastbound Staircase Closed for Repairs - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1575048',
        },
      ],
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
        {
          advisory_id: '1755614',
          pub_date: '20240528 14:52:30',
          text: 'Northeast Corridor and North Jersey Coast Line: Possible Delays due to Boarding/Detraining Adjustments – Beginning Friday, June 7, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755614',
        },
        {
          advisory_id: '1755605',
          pub_date: '20240528 14:46:29',
          text: 'Rahway, Elizabeth and North Elizabeth Stations: Possible Delays due to Boarding/Detraining Adjustments – Beginning Friday, June 7, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755605',
        },
        {
          advisory_id: '1755599',
          pub_date: '20240528 14:35:35',
          text: 'Linden Station: Possible Delays due to Boarding/Detraining Adjustments – Beginning Friday, June 7, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755599',
        },
        {
          advisory_id: '1590805',
          pub_date: '20230328 13:32:56',
          text: 'Northeast Corridor, North Jersey Coast Line and Morris and Essex Lines: Possible Delays due to Infrastructure Maintenance and Construction of Future Improvements – Weekends Until Further Notice',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1590805',
        },
      ],
    },
    {
      name: 'MNBN',
      STATION_ADVISORY: [
        {
          advisory_id: '1766621',
          pub_date: '20240620 12:00:06',
          text: 'Ridgewood Station: East-End Staircase Closed – Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1766621',
        },
        {
          advisory_id: '1755470',
          pub_date: '20240528 08:12:53',
          text: 'Hoboken Terminal: Women’s Restroom Closed for Renovation – Saturday, June 8, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755470',
        },
        {
          advisory_id: '1731345',
          pub_date: '20240325 11:16:34',
          text: 'Mahwah Station: Temporary Parking Updates - Effective Monday, April 1, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1731345',
        },
        {
          advisory_id: '1667201',
          pub_date: '20231006 07:26:38',
          text: 'Secaucus Junction: Track 2 Partial Eastbound Platform Closure - Effective October 5, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1667201',
        },
        {
          advisory_id: '1470775',
          pub_date: '20220127 10:38:20',
          text: 'Hoboken Terminal: Boarding Changes for Resiliency Project - Beginning February 2022',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1470775',
        },
      ],
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
    },
    {
      name: 'RARV',
      STATION_ADVISORY: [
        {
          advisory_id: '1766297',
          pub_date: '20240620 06:58:39',
          text: 'UPDATE: Newark Penn Station: Track 1-PATH Passenger Elevator 37 Returned to Service - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1766297',
        },
        {
          advisory_id: '1765373',
          pub_date: '20240618 19:06:24',
          text: 'Plainfield Station: Eastbound Elevator Temporarily Out of Service for Repairs - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1765373',
        },
        {
          advisory_id: '1731699',
          pub_date: '20240326 12:04:00',
          text: 'Newark Penn Station: Track 5 Passenger Elevator 42 Temporarily Out of Service - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1731699',
        },
        {
          advisory_id: '1667201',
          pub_date: '20231006 07:26:38',
          text: 'Secaucus Junction: Track 2 Partial Eastbound Platform Closure - Effective October 5, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1667201',
        },
        {
          advisory_id: '1616666',
          pub_date: '20230615 10:48:49',
          text: 'Roselle Park Station: ADA Improvement Project Underway – Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1616666',
        },
      ],
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
    },
    {
      name: 'BNTN',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
      STATION_ADVISORY: [
        {
          advisory_id: '1755470',
          pub_date: '20240528 08:12:53',
          text: 'Hoboken Terminal: Women’s Restroom Closed for Renovation – Saturday, June 8, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755470',
        },
        {
          advisory_id: '1667201',
          pub_date: '20231006 07:26:38',
          text: 'Secaucus Junction: Track 2 Partial Eastbound Platform Closure - Effective October 5, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1667201',
        },
        {
          advisory_id: '1470775',
          pub_date: '20220127 10:38:20',
          text: 'Hoboken Terminal: Boarding Changes for Resiliency Project - Beginning February 2022',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1470775',
        },
      ],
    },
    {
      name: 'BNTNM',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
    },
    {
      name: 'MNBNP',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
    },
    {
      name: 'MNE',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
        {
          advisory_id: '1751945',
          pub_date: '20240520 09:17:00',
          text: 'Morris and Essex Line: Possible Delays due to Track Work – Saturday, June 22 to Sunday, June 23, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1751945',
        },
        {
          advisory_id: '1590805',
          pub_date: '20230328 13:32:56',
          text: 'Northeast Corridor, North Jersey Coast Line and Morris and Essex Lines: Possible Delays due to Infrastructure Maintenance and Construction of Future Improvements – Weekends Until Further Notice',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1590805',
        },
      ],
      STATION_ADVISORY: [
        {
          advisory_id: '1755470',
          pub_date: '20240528 08:12:53',
          text: 'Hoboken Terminal: Women’s Restroom Closed for Renovation – Saturday, June 8, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755470',
        },
        {
          advisory_id: '1667201',
          pub_date: '20231006 07:26:38',
          text: 'Secaucus Junction: Track 2 Partial Eastbound Platform Closure - Effective October 5, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1667201',
        },
        {
          advisory_id: '1470775',
          pub_date: '20220127 10:38:20',
          text: 'Hoboken Terminal: Boarding Changes for Resiliency Project - Beginning February 2022',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1470775',
        },
      ],
    },
    {
      name: 'MNEG',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
      STATION_ADVISORY: [
        {
          advisory_id: '1755470',
          pub_date: '20240528 08:12:53',
          text: 'Hoboken Terminal: Women’s Restroom Closed for Renovation – Saturday, June 8, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755470',
        },
        {
          advisory_id: '1470775',
          pub_date: '20220127 10:38:20',
          text: 'Hoboken Terminal: Boarding Changes for Resiliency Project - Beginning February 2022',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1470775',
        },
      ],
    },
    {
      name: 'NJCLL',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
    },
    {
      name: 'PASC',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
      STATION_ADVISORY: [
        {
          advisory_id: '1755470',
          pub_date: '20240528 08:12:53',
          text: 'Hoboken Terminal: Women’s Restroom Closed for Renovation – Saturday, June 8, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1755470',
        },
        {
          advisory_id: '1667201',
          pub_date: '20231006 07:26:38',
          text: 'Secaucus Junction: Track 2 Partial Eastbound Platform Closure - Effective October 5, 2023',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1667201',
        },
        {
          advisory_id: '1470775',
          pub_date: '20220127 10:38:20',
          text: 'Hoboken Terminal: Boarding Changes for Resiliency Project - Beginning February 2022',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1470775',
        },
      ],
    },
    {
      name: 'PRIN',
      SERVICE_ADVISORY: [
        {
          advisory_id: '1764185',
          pub_date: '20240617 14:05:54',
          text: 'MetLife Stadium: NJ TRANSIT Offers Rail Service between Secaucus Junction and MetLife Stadium for COPA America Soccer Matches – Tuesday, June 25, and Thursday, June 27, 2024',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1764185',
        },
      ],
    },
    {
      name: 'ATLC',
      STATION_ADVISORY: [
        {
          advisory_id: '1674426',
          pub_date: '20231024 08:58:46',
          text: 'Lindenwold Station: Waiting Room Closed - Effective Immediately',
          advisory_alert: '',
          link: 'https://www.njtransit.com/node/1674426',
        },
      ],
    },
  ],
};
